# fly.toml app configuration file generated for tdr-bot on 2023-08-14T11:56:56-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tdr-bot"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
