name: Prod deploy

on:
  push:
    paths:
      - '*.js'
      - '*.ts'
      - 'Dockerfile'
      - 'fly.tmol'
      - 'package.json'
      - 'public/**'
      - 'src/**'
      - 'tsconfig.json'
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
